name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 10 1 * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 📥 جلب المشروع
      - name: Checkout
        uses: actions/checkout@v4

      # 📅 تاريخ للكاش
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

      # ⚡ Cache Buildozer global
      - name: Cache Buildozer global
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # ⚡ Cache Buildozer local
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-

      # 📦 تثبيت dependencies (FIX libtinfo)
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo6 \
            cmake libffi-dev libssl-dev

      # 🐍 تثبيت Buildozer
      - name: Install Buildozer
        run: |
          pip3 install --user --upgrade buildozer Cython virtualenv
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 🤖 Build APK
      - name: Build APK
        run: |
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          buildozer android debug

      # 📤 رفع APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: bin/*.apk
